#!/usr/bin/env bash
# Regenerate public/fonts/ from the Google Fonts css2 API.
#
# The app must render on a restricted-egress LAN, so the webfonts are served
# from our own origin rather than @import'ed from fonts.googleapis.com at
# runtime. Run this only when the font stack in EILViz.jsx changes; the output
# is committed.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="public/fonts"
UA='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
CSS_URL='https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=DM+Sans:wght@300;400;500;700&display=swap'

mkdir -p "$OUT"
rm -f "$OUT"/*.woff2 "$OUT"/fonts.css
curl -fsSL -A "$UA" "$CSS_URL" -o "$OUT/.upstream.css"

OUT="$OUT" python3 - <<'PY'
import os, re, subprocess

out = os.environ["OUT"]
upstream = os.path.join(out, ".upstream.css")
with open(upstream) as fh:
    css = fh.read()

# Each block is a "/* subset */" comment followed by one @font-face rule.
# Only latin and latin-ext are needed; the rest is dead weight in the bundle.
blocks = re.findall(r"/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})", css, re.S)
if not blocks:
    raise SystemExit("no @font-face blocks parsed from the css2 response")

seen, kept = {}, []
for subset, rule in blocks:
    if subset not in {"latin", "latin-ext"}:
        continue
    url = re.search(r"url\((https://[^)]+\.woff2)\)", rule).group(1)
    if url not in seen:
        family = re.search(r"font-family: '([^']+)'", rule).group(1)
        name = f"{family.lower().replace(' ', '-')}-{len(seen)}.woff2"
        subprocess.run(["curl", "-fsSL", url, "-o", os.path.join(out, name)], check=True)
        seen[url] = name
    kept.append(rule.replace(url, f"/fonts/{seen[url]}"))

header = (
    "/* Vendored Google Fonts — DM Sans and Space Mono, latin + latin-ext.\n"
    " * Generated by scripts/vendor-fonts.sh; do not edit by hand.\n"
    " * Served from our own origin so the app renders without egress to\n"
    " * fonts.googleapis.com. */\n\n"
)
with open(os.path.join(out, "fonts.css"), "w") as fh:
    fh.write(header + "\n\n".join(kept) + "\n")
print(f"{len(seen)} woff2 files, {len(kept)} @font-face rules")
PY

rm -f "$OUT/.upstream.css"
